namespace StepTrail.Shared.Entities;

/// <summary>
/// Persisted record of an alert that was generated by the runtime.
/// Each alert can have one or more delivery attempts through different channels.
/// </summary>
public class AlertRecord
{
    public Guid Id { get; set; }
    public string AlertType { get; set; } = string.Empty;
    public Guid WorkflowInstanceId { get; set; }
    public string? WorkflowKey { get; set; }
    public string? StepKey { get; set; }
    public int Attempt { get; set; }
    public string? Cause { get; set; }
    public DateTimeOffset GeneratedAtUtc { get; set; }

    public ICollection<AlertDeliveryRecord> Deliveries { get; set; } = [];
}
